### ISSUE TITLE
Empty stream windows

### ISSUE THREAD

**Issue by foxdonut** [foxdonut/meiosis-tracer#2]
As reported by @smuemd, multiple duplicate empty stream windows show up in the tracer when using [browser-sync](https://github.com/Browsersync/browser-sync)

![](https://files.gitter.im/foxdonut/meiosis/uKr7/image.png)

**Comment by smuemd** [comment]
Here is my spike `app.js` config for reproducing this

```js
const htmlStandards = require('reshape-standard')
const cssStandards = require('spike-css-standards')
const jsStandards = require('spike-js-standards')
const react = require('babel-preset-react')

const env = process.env.SPIKE_ENV

module.exports = {
  babel: jsStandards({ appendPresets: [[react]] }),
  devtool: 'source-map',
  entry: {
    'js/main': [ env === 'production' ? './assets/js/index.js' : './assets/js/_dev.js' ]
  },
  ignore: ['.**/**', '**/layout.html', '**/_*', '**/.*', 'readme.md', 'yarn.lock', 'package-lock.json'],
  postcss: cssStandards({
    minify: env === 'production',
    warnForDuplicates: env !== 'production'
  }),
  reshape: htmlStandards({
    locals: (ctx) => { return { foo: 'bar' } },
    minify: env === 'production'
  }),
  vendor: 'assets/vendor/**'
}
```

the entry file is in `assets/js/_dev.js`

and looks like this

```js
import meiosisTracer from 'meiosis-tracer'
import initialized from './index'

initialized
  .then(Main => {
    const models = Main.models
    meiosisTracer({
      streams: [ models ]
      // streams: [{ stream: models, label: 'mysuperstream' }]
    })
  })
  .catch(err => console.log(err))
```

**Comment by smuemd** [comment]
@foxdonut 
I tested on v 2.0.1 now.
the empty windows are gone (yay!)

But it looks like autorefresh is breaking the tracer anyway.
Here is what I observed
- When triggering an auto refresh while having the dev tools open in the browser, the tracer freezes.
- triggering an auto update and opening the dev tools afterwards, everything is fine.

**Comment by foxdonut** [comment]
@smuemd would you mind testing with v 2.0.2? Thanks again, much appreciated!

**Comment by smuemd** [comment]
v2.0.2 shows the same behaviour
also closing the dev-tools and refreshing the page manually seems to bring the tracer back to life.

**Comment by foxdonut** [comment]
@smuemd thanks! I will look into it.

**Comment by foxdonut** [comment]
@smuemd I tried with Wright and it was working well. If auto-refresh with spike is causing problems, as you said best thing is to close devtools and re-open.
