### ISSUE TITLE
In Chrome DevTools, Tracer stops working after reloading the page

### ISSUE THREAD

**Issue by foxdonut** [foxdonut/meiosis-tracer#3]
In Chrome DevTools, Tracer stops working after reloading the page.

Until this issue is fixed, the workaround is to close and re-open Chrome DevTools after reloading the page.

**Comment by jmzagorski** [comment]
Thanks for such a great pattern. I am using your pattern with the Aurelia framework and it works wonderfully. Have you found any other workaround besides re-opening chrome devtools?

**Comment by foxdonut** [comment]
@jmzagorski thank you, that is great to hear!

I had not found a solution at the time, but I will have another look to see if there is a way.

**Comment by jmzagorski** [comment]
Thank you. In the meantime I thought about integrating with redux dev tools.

**Comment by foxdonut** [comment]
@jmzagorski it seems like it will take some time for my update to be published in the Chrome Web Store. Would you mind trying out the update and letting me know if it works for you?

```
git clone https://github.com/foxdonut/meiosis-tracer
```

Then, in Chrome:

- open `chrome://extensions/`
- enable Developer Mode
- turn off Meiosis Tracer 3.0.0
- click on `Load unpacked`
- select the `meiosis-tracer/chrome-devtool` directory

This should show up as Meiosis Tracer 4.0.0.

The tracer should continue working after reloading the page.

Please let me know if you are able to try it out. Thank you!

**Comment by jmzagorski** [comment]
Did i miss a step? I get this error:

`Uncaught TypeError: window.meiosisTracer is not a function` pointing to this code:

```
  tracer = window.meiosisTracer({
    selector: "#meiosis-tracer",
    sendTracerInit: sendTracerInit,
    triggerStreamValue: triggerStreamValue,
    direction: "auto",
    theme: chrome.devtools.panels.themeName
  })
```

**Comment by foxdonut** [comment]
@jmzagorski my apologies, I am the one who missed some steps:

```
cd meiosis-tracer
npm ci
npm start
```

Also in your project:

```
npm uninstall meiosis-tracer
npm i -D meiosis-tracer
# and the command you use to rebuild your project
```

In the `chrome://extensions/` tab, press reload (the circle arrow) on Meiosis Tracer 4.0.0.

You'll need to close and re-open devtools for the change to take effect.

Sorry about that, I hope this works.

**Comment by foxdonut** [comment]
P.S. as an alternative to trying out in your project, you can try on this example: http://meiosis.js.org/examples/todomvc/index.html

**Comment by jmzagorski** [comment]
ahh should have read the docs! I would have forgot to reinstall my devDep in my app though. Did a small test and it seems to be working. Great job!

**Comment by foxdonut** [comment]
@jmzagorski thank you for trying it out! I will publish the update to the Chrome web store as soon as it is approved.

**Comment by foxdonut** [comment]
@jmzagorski just wanted to say thank you for your kind words regarding Meiosis, I am very happy to hear that it is useful. I'm glad you brought my attention back to this issue, it motivated me to have another look at it, and the tracer is now improved! :+1:
