### ISSUE TITLE
Chrome Dark Mode: Styling isn't visible

### ISSUE THREAD

**Issue by sjmik** [foxdonut/meiosis-tracer#5]
![image](https://user-images.githubusercontent.com/8127593/62966457-16388f80-bdd5-11e9-9714-192e0bf509d6.png)
![image](https://user-images.githubusercontent.com/8127593/62966414-fc974800-bdd4-11e9-8dab-8ea76ad51f67.png)

**Comment by foxdonut** [comment]
Good find @sjmik thank you, I will look into it.

**Comment by foxdonut** [comment]
@sjmik would you mind trying it out before I publish?

```
git clone https://github.com/foxdonut/meiosis-tracer
cd meiosis-tracer
npm ci
npm start
```

- In Chrome, open chrome://extensions
- Disable or remove the previous version of Meiosis-Tracer
- Press Load unpacked
- Select the chrome-devtool directory under meiosis-tracer

**Comment by sjmik** [comment]
Looks good, thanks!

![image](https://user-images.githubusercontent.com/8127593/63117653-3b123b80-bf6a-11e9-956a-e6044ea4cf9e.png)
![image](https://user-images.githubusercontent.com/8127593/63117662-3ea5c280-bf6a-11e9-9d91-f37f2e297dfb.png)

(Side note, I needed to open a new tab after changing theme between dark and light; nothing worth worrying about, I think)

**Comment by foxdonut** [comment]
Thank you @sjmik , the update is now available from the [Chrome Web Store](https://chrome.google.com/webstore/detail/meiosis-tracer/lcomllmppaiciocfbeefdeoplnfpnnfl).
